import { AnalyticsEvent, type AnalyticsEventName } from './events';

export type NonClientEventDisposition = 'planned' | 'server_only' | 'deprecated';

const planned = [
  AnalyticsEvent.RecipeCookingOpened,
  AnalyticsEvent.RecipeExported,
  AnalyticsEvent.RecipeDeleted,
  AnalyticsEvent.AgentOpenedFromCapability,
  AnalyticsEvent.AgentReturnedToCapability,
  AnalyticsEvent.MoneyRebalanceCancelled,
  AnalyticsEvent.MoneyBudgetRecoveryInvoked,
  AnalyticsEvent.ShareInviteKindSelected,
  AnalyticsEvent.ShareCoachmarkShown,
  AnalyticsEvent.ShareCoachmarkDismissed,
  AnalyticsEvent.SharedGoalCheckinNudgeTapped,
  AnalyticsEvent.CheckinDraftEdited,
  AnalyticsEvent.CheckinDraftReapprovalRequired,
  AnalyticsEvent.PendingDraftIndicatorShown,
  AnalyticsEvent.PendingDraftIndicatorTapped,
  AnalyticsEvent.PendingDraftCardShown,
  AnalyticsEvent.EndOfDayReviewShown,
  AnalyticsEvent.EndOfDayReviewDismissed,
  AnalyticsEvent.EndOfDayReviewSent,
  AnalyticsEvent.ManualComposerOpened,
  AnalyticsEvent.AppPartnerNotificationOpened,
  AnalyticsEvent.AppPartnerCheerSent,
  AnalyticsEvent.AppPartnerReplySent,
  AnalyticsEvent.ProPreviewGranted,
  AnalyticsEvent.ScreenTimeSetupAbandoned,
  AnalyticsEvent.ChapterSectionExpanded,
  AnalyticsEvent.FriendInviteCreated,
  AnalyticsEvent.FriendInviteShared,
  AnalyticsEvent.FriendInviteAccepted,
  AnalyticsEvent.FriendRequestAccepted,
  AnalyticsEvent.FriendRequestDeclined,
  AnalyticsEvent.FriendsListViewed,
] as const;

const serverOnly = [
  AnalyticsEvent.PhoneAgentLinkCodeRequested,
  AnalyticsEvent.PhoneAgentLinked,
  AnalyticsEvent.PhoneAgentSmsCaptured,
  AnalyticsEvent.PhoneAgentPersonRemembered,
  AnalyticsEvent.PhoneAgentMemorySaved,
  AnalyticsEvent.PhoneAgentEventSaved,
  AnalyticsEvent.PhoneAgentCadenceSaved,
  AnalyticsEvent.PhoneAgentFollowupSent,
  AnalyticsEvent.PhoneAgentLoopClosed,
  AnalyticsEvent.PhoneAgentPromptSnoozed,
  AnalyticsEvent.PhoneAgentPromptPaused,
  AnalyticsEvent.PhoneAgentRevoked,
  AnalyticsEvent.ShareWebInviteViewed,
  AnalyticsEvent.ShareWebCheerSent,
  AnalyticsEvent.SharePartnerOptedIn,
  AnalyticsEvent.SharePartnerAccountCreated,
  AnalyticsEvent.SharePartnerFirstGoalCreated,
  AnalyticsEvent.ShareSeedCheerSent,
  AnalyticsEvent.SharePartnerUnsubscribed,
  AnalyticsEvent.ShareQuietGoalNudgeSent,
  AnalyticsEvent.ShareQuietGoalNudgeActed,
  AnalyticsEvent.ShareWebReplySent,
  AnalyticsEvent.InviteLandingActionSelected,
  AnalyticsEvent.InviteLandingViewed,
  AnalyticsEvent.InviteLandingInstallCtaSelected,
  AnalyticsEvent.PartnerGoalCreated,
  AnalyticsEvent.PartnerInviteSent,
  AnalyticsEvent.MilestoneRecordFailed,
] as const;

export const NON_CLIENT_EVENT_DISPOSITIONS: Partial<Record<AnalyticsEventName, NonClientEventDisposition>> = {
  ...Object.fromEntries(planned.map((event) => [event, 'planned'] as const)),
  ...Object.fromEntries(serverOnly.map((event) => [event, 'server_only'] as const)),
};
