import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { corsHeaders } from '../_shared/cors.ts';
import { decryptToken, encryptToken, type EncryptedToken } from '../_shared/calendarUtils.ts';
import { getAuthenticatedUser, isAuthenticationError } from '../_shared/supabase.ts';
import { addToKrogerCart, getKrogerClientToken, refreshKrogerToken, RetailerAdapterError, searchKrogerLocations, searchKrogerProducts, type KrogerProduct } from '../_shared/krogerAdapter.ts';
import { excludeCartedGroceryItems, excludeCartedProductMappings, retailerCartCounts } from '../_shared/groceryRetailerCart.ts';
import { isKrogerLocationConfirmationValid, krogerCartUrlForBanner, resolveKrogerShoppingLocation } from '../_shared/krogerShoppingLocation.ts';

const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'content-type':'application/json'}});
const env=(name:string)=>Deno.env.get(name)?.trim()||null;
const uuid=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const clean=(value:unknown,max=240)=>typeof value==='string'?value.trim().slice(0,max):'';
const safeQuantity=(value:unknown)=>Number.isFinite(Number(value))&&Number(value)>0?Math.max(1,Math.ceil(Number(value))):1;
async function hash(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(bytes)].map(v=>v.toString(16).padStart(2,'0')).join('');}
type TokenPayload={access:EncryptedToken;refresh:EncryptedToken|null;tokenType:string;scope:string[]};
async function cartReceiptSummary(admin:any,handoffId:string,listId:string){const[{data:handoffReceipts,error:handoffReceiptError},{data:needed,error:neededError}]=await Promise.all([admin.from('kwilt_retailer_handoff_items').select('grocery_item_id').eq('retailer_handoff_id',handoffId),admin.from('kwilt_grocery_items').select('id').eq('grocery_list_id',listId).eq('state','needed')]);if(handoffReceiptError)throw handoffReceiptError;if(neededError)throw neededError;const neededIds=(needed??[]).map((row:any)=>row.id);const {data:allReceipts,error:allReceiptError}=neededIds.length?await admin.from('kwilt_retailer_handoff_items').select('grocery_item_id').in('grocery_item_id',neededIds):{data:[],error:null};if(allReceiptError)throw allReceiptError;return retailerCartCounts(neededIds,allReceipts??[],handoffReceipts??[]);}

serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders}); if(req.method!=='POST')return json(405,{error:{code:'method_not_allowed'}});
 try{
  const enabled=env('FOOD_KROGER_HANDOFF_ENABLED')==='true',clientId=env('KROGER_CLIENT_ID'),clientSecret=env('KROGER_CLIENT_SECRET'),tokenSecret=env('KROGER_TOKEN_SECRET'); if(!enabled||!clientId||!clientSecret||!tokenSecret)return json(503,{error:{code:'provider_unavailable',message:'Kroger online shopping is not configured yet.'}});
  const {supabase:admin,user}=await getAuthenticatedUser(req); const body=await req.json().catch(()=>null) as Record<string,unknown>|null; const action=clean(body?.action,40);
  const {data:binding}=await admin.from('kwilt_person_auth_bindings').select('person_id').eq('user_id',user.id).eq('status','active').maybeSingle(); if(!binding?.person_id)return json(409,{error:{code:'person_binding_required'}});
  const {data:account}=await admin.from('kwilt_grocery_provider_accounts').select('id,state,scopes,retailer_label,location_id,location_name,location_address,access_expires_at').eq('owner_person_id',binding.person_id).eq('provider','kroger').maybeSingle();
  if(action==='status')return json(200,{configured:true,connection:account?{state:account.state,retailerLabel:account.retailer_label??'Kroger',location:account.location_id?{id:account.location_id,name:account.location_name,address:account.location_address}:null,capabilities:{productMatch:true,cartAdd:Array.isArray(account.scopes)&&account.scopes.includes('cart.basic:write')}}:null});
  if(action==='locations'){const zip=clean(body?.zipCode,10);if(!/^\d{5}$/.test(zip))return json(400,{error:{code:'invalid_zip'}});const token=await getKrogerClientToken({clientId,clientSecret});return json(200,{locations:await searchKrogerLocations({zipCode:zip,token:token.accessToken})});}
  if(action==='prepare_matches'){
   if(!uuid(body?.groceryListId)||!Number.isInteger(body?.expectedRevision))return json(400,{error:{code:'invalid_request'}});const listId=body.groceryListId as string,revision=Number(body.expectedRevision);
   const shoppingLocation=resolveKrogerShoppingLocation(body?.location,account);if(!shoppingLocation)return json(409,{error:{code:'location_required'}});
   const {data:list}=await admin.from('kwilt_grocery_lists').select('id,owner_person_id,revision,status').eq('id',listId).maybeSingle();if(!list||list.owner_person_id!==binding.person_id)return json(404,{error:{code:'grocery_list_not_found'}});if(list.revision!==revision||list.status!=='ready')return json(409,{error:{code:'stale_or_unreviewed_grocery_list'}});
   const {data:items,error:itemError}=await admin.from('kwilt_grocery_items').select('id,concept,quantity_min,quantity_max,unit,note,position').eq('grocery_list_id',listId).eq('state','needed').order('position').limit(50);if(itemError)throw itemError;const itemIds=(items??[]).map((item:any)=>item.id);const {data:receipts,error:receiptError}=itemIds.length?await admin.from('kwilt_retailer_handoff_items').select('grocery_item_id').in('grocery_item_id',itemIds):{data:[],error:null};if(receiptError)throw receiptError;
   const providerToken=await getKrogerClientToken({clientId,clientSecret});const matches=[];for(const item of excludeCartedGroceryItems(items??[],receipts??[])){const products=await searchKrogerProducts({term:item.concept,locationId:shoppingLocation.id,token:providerToken.accessToken});matches.push({groceryItem:{id:item.id,concept:item.concept,quantity:safeQuantity(item.quantity_min),unit:item.unit},products});}
   return json(200,{retailerLabel:shoppingLocation.banner,location:shoppingLocation,matches});
  }
  if(action==='confirm_mapping'){
   if(!uuid(body?.groceryListId)||!uuid(body?.groceryItemId))return json(400,{error:{code:'invalid_request'}});const product=body?.product&&typeof body.product==='object'?body.product as KrogerProduct:null;if(!product||!clean(product.upc,40)||!clean(product.title))return json(400,{error:{code:'invalid_product'}});
   const shoppingLocation=resolveKrogerShoppingLocation(body?.location,account);if(!shoppingLocation)return json(409,{error:{code:'location_required'}});
   const {data:item}=await admin.from('kwilt_grocery_items').select('id,grocery_list_id').eq('id',body.groceryItemId).eq('grocery_list_id',body.groceryListId).maybeSingle();const {data:list}=await admin.from('kwilt_grocery_lists').select('owner_person_id').eq('id',body.groceryListId).maybeSingle();if(!item||!list||list.owner_person_id!==binding.person_id)return json(404,{error:{code:'grocery_item_not_found'}});
   await admin.from('kwilt_grocery_product_mappings').update({state:'rejected'}).eq('grocery_item_id',body.groceryItemId).eq('provider','kroger').eq('state','confirmed');
   const {data:mapping,error:mappingError}=await admin.from('kwilt_grocery_product_mappings').upsert({grocery_list_id:body.groceryListId,grocery_item_id:body.groceryItemId,provider:'kroger',retailer_product_id:clean(product.upc,40),title:clean(product.title),store_name:shoppingLocation.name,location_id:shoppingLocation.id,package_base_units:1,quantity:safeQuantity(body.quantity),state:'confirmed',confirmed_by_person_id:binding.person_id},{onConflict:'grocery_item_id,provider,retailer_product_id'}).select('id').single();if(mappingError)throw mappingError;return json(200,{mappingId:mapping.id,state:'confirmed'});
  }
  if(!account||account.state!=='active')return json(409,{error:{code:'provider_connection_required'}});
  if(action==='select_location'){const shoppingLocation=resolveKrogerShoppingLocation(body?.location,null);if(!shoppingLocation)return json(400,{error:{code:'invalid_location'}});await admin.from('kwilt_grocery_provider_accounts').update({location_id:shoppingLocation.id,location_name:shoppingLocation.name,location_address:shoppingLocation.address,retailer_label:shoppingLocation.banner,updated_at:new Date().toISOString()}).eq('id',account.id);return json(200,{location:shoppingLocation});}
  if(!account.location_id)return json(409,{error:{code:'location_required'}});
  if(action==='cart_add'){
   if(!uuid(body?.groceryListId)||!Number.isInteger(body?.expectedRevision))return json(400,{error:{code:'invalid_request'}});const listId=body.groceryListId as string,revision=Number(body.expectedRevision);const {data:list}=await admin.from('kwilt_grocery_lists').select('owner_person_id,revision,status').eq('id',listId).maybeSingle();if(!list||list.owner_person_id!==binding.person_id)return json(404,{error:{code:'grocery_list_not_found'}});if(list.revision!==revision||list.status!=='ready')return json(409,{error:{code:'stale_or_unreviewed_grocery_list'}});
   if(!isKrogerLocationConfirmationValid(body?.locationConfirmation,account.location_id))return json(409,{error:{code:'retailer_store_confirmation_required'}});
   const {data:mappings}=await admin.from('kwilt_grocery_product_mappings').select('id,grocery_item_id,retailer_product_id,quantity').eq('grocery_list_id',listId).eq('provider','kroger').eq('location_id',account.location_id).eq('state','confirmed').order('created_at');if(!mappings?.length)return json(409,{error:{code:'confirmed_products_required'}});const mappingItemIds=mappings.map((row:any)=>row.grocery_item_id);const {data:priorReceipts,error:priorReceiptError}=await admin.from('kwilt_retailer_handoff_items').select('grocery_item_id').in('grocery_item_id',mappingItemIds);if(priorReceiptError)throw priorReceiptError;const pendingMappings=excludeCartedProductMappings(mappings,priorReceipts??[]);if(!pendingMappings.length)return json(409,{error:{code:'no_remaining_products'}});const cartItems=pendingMappings.map((row:any)=>({upc:row.retailer_product_id,quantity:row.quantity}));const payloadHash=await hash(cartItems),key=`kroger:${listId}:${revision}:${payloadHash}`;
   const cartUrl=krogerCartUrlForBanner(account.retailer_label);const {data:existing}=await admin.from('kwilt_retailer_handoffs').select('id,state,private_url').eq('idempotency_key',key).maybeSingle();if(existing?.state==='cart_add_acknowledged'){if(existing.private_url!==cartUrl)await admin.from('kwilt_retailer_handoffs').update({private_url:cartUrl,updated_at:new Date().toISOString()}).eq('id',existing.id);const summary=await cartReceiptSummary(admin,existing.id,listId);return json(200,{handoffId:existing.id,state:existing.state,cartUrl,retailerLabel:account.retailer_label??"Smith's",...summary,replayed:true});}if(existing?.state==='confirmation_required')return json(409,{error:{code:'check_retailer_cart',handoffId:existing.id}});if(existing?.state==='cart_add_requested')return json(409,{error:{code:'handoff_in_progress'}});
   let handoffId=existing?.id;if(!handoffId){const {data:inserted,error}=await admin.from('kwilt_retailer_handoffs').insert({grocery_list_id:listId,grocery_list_revision:revision,provider:'kroger',idempotency_key:key,payload_hash:payloadHash,state:'cart_add_requested',next_step:'Review products, confirm the retailer pickup store, substitutions, pickup slot, payment, and checkout.'}).select('id').single();if(error)throw error;handoffId=inserted.id;}else await admin.from('kwilt_retailer_handoffs').update({state:'cart_add_requested',updated_at:new Date().toISOString()}).eq('id',handoffId);
   const {data:tokenRow}=await admin.from('kwilt_grocery_provider_tokens').select('token_payload,expires_at').eq('account_id',account.id).maybeSingle();const payload=tokenRow?.token_payload as TokenPayload|undefined;if(!payload)return json(409,{error:{code:'provider_connection_required'}});let access=await decryptToken(tokenSecret,payload.access),refresh=payload.refresh?await decryptToken(tokenSecret,payload.refresh):null;if(!access)return json(409,{error:{code:'provider_connection_required'}});
   if(tokenRow?.expires_at&&Date.parse(tokenRow.expires_at)<Date.now()+60000){if(!refresh)return json(409,{error:{code:'provider_reconnect_required'}});const renewed=await refreshKrogerToken({clientId,clientSecret,refreshToken:refresh});access=renewed.accessToken;refresh=renewed.refreshToken??refresh;const expiresAt=new Date(Date.now()+renewed.expiresIn*1000).toISOString();await admin.from('kwilt_grocery_provider_tokens').update({token_payload:{access:await encryptToken(tokenSecret,access),refresh:refresh?await encryptToken(tokenSecret,refresh):null,tokenType:renewed.tokenType,scope:renewed.scope},expires_at:expiresAt,updated_at:new Date().toISOString()}).eq('account_id',account.id);}
   try{await addToKrogerCart({items:cartItems,accessToken:access});}catch(error){const ambiguous=error instanceof RetailerAdapterError&&error.message==='provider_write_ambiguous';await admin.from('kwilt_retailer_handoffs').update({state:ambiguous?'confirmation_required':'failed',updated_at:new Date().toISOString()}).eq('id',handoffId);if(ambiguous)return json(409,{error:{code:'check_retailer_cart',handoffId}});throw error;}const {data:receipt,error:receiptError}=await admin.rpc('acknowledge_kwilt_retailer_cart_add',{p_handoff_id:handoffId,p_mapping_ids:pendingMappings.map((row:any)=>row.id),p_retailer_label:account.retailer_label??"Smith's",p_location_id:account.location_id,p_location_name:account.location_name,p_cart_url:cartUrl});if(receiptError){await admin.from('kwilt_retailer_handoffs').update({state:'confirmation_required',updated_at:new Date().toISOString()}).eq('id',handoffId);return json(409,{error:{code:'check_retailer_cart',handoffId}});}await admin.from('kwilt_grocery_provider_accounts').update({last_used_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',account.id);return json(200,{handoffId,state:'cart_add_acknowledged',cartUrl,retailerLabel:account.retailer_label??"Smith's",...receipt,replayed:false});
  }
  return json(400,{error:{code:'unknown_action'}});
 }catch(error){const unauthorized=isAuthenticationError(error);const code=error instanceof RetailerAdapterError?error.message:unauthorized?'unauthorized':'kroger_api_failed';const status=unauthorized?401:code==='provider_rate_limited'?429:code==='provider_unavailable'?503:500;return json(status,{error:{code,message:status===503?'Online shopping is unavailable. Your plain list is still ready.':'The retailer request could not be completed.'}});}
});
