import { fireEvent, render, waitFor } from '@testing-library/react-native';
import type { ReactNode } from 'react';
import * as WebBrowser from 'expo-web-browser';

const mockStatus=jest.fn();const mockConnect=jest.fn();const mockSearchLocations=jest.fn();const mockSelectLocation=jest.fn();const mockPrepareMatches=jest.fn();const mockConfirmMapping=jest.fn();const mockCartAdd=jest.fn();
jest.mock('../data/krogerConnectionRepository',()=>({createKrogerConnectionRepository:()=>({status:mockStatus,connect:mockConnect,searchLocations:mockSearchLocations,selectLocation:mockSelectLocation,prepareMatches:mockPrepareMatches,confirmMapping:mockConfirmMapping,cartAdd:mockCartAdd})}));
jest.mock('../data/groceryRepository',()=>({createGroceryRepository:()=>({list:jest.fn().mockResolvedValue([{id:'list-1',revision:2,status:'ready',items:[{id:'one',state:'needed',retailerCart:null},{id:'two',state:'needed',retailerCart:null}]}])})}));
jest.mock('../data/preferredGroceryStore',()=>({preferredGroceryStore:{read:jest.fn(),write:jest.fn()}}));
jest.mock('../../../services/LocationPermissionService',()=>({LocationPermissionService:{syncOsPermissionStatus:jest.fn(),ensurePermissionWithRationale:jest.fn()}}));
jest.mock('../../../services/location/currentLocation',()=>({getCurrentStoreSearchContextBestEffort:jest.fn(),geocodeStoreSearchBestEffort:jest.fn(),hydrateStoreCoordinatesBestEffort:jest.fn(async (locations:unknown[])=>locations)}));
jest.mock('../../../store/useAppStore',()=>({useAppStore:(selector:(state:{authIdentity:{userId:string}})=>unknown)=>selector({authIdentity:{userId:'user-1'}})}));
jest.mock('expo-web-browser',()=>({openBrowserAsync:jest.fn(),maybeCompleteAuthSession:jest.fn()}));
jest.mock('react-native-maps',()=>{const React=require('react');const{View}=require('react-native');const Map=({children,...props}:{children?:ReactNode;testID?:string})=>React.createElement(View,props,children);const Marker=({title,description}:{title?:string;description?:string})=>React.createElement(View,{accessibilityLabel:[title,description].filter(Boolean).join('. ')});return{__esModule:true,default:Map,Marker};});
jest.mock('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,right:0,bottom:24,left:0})}));
jest.mock('../../../ui/layout/AppShell',()=>({AppShell:({children}:{children:ReactNode})=>children}));
jest.mock('../../../ui/layout/PageHeader',()=>{const {Text}=require('react-native');return {PageHeader:({title,rightElement}:{title:string;rightElement?:ReactNode})=><><Text>{title}</Text>{rightElement}</>};});
jest.mock('../../../ui/layout/BottomDrawerHeader',()=>{const{Text}=require('react-native');return{BottomDrawerHeader:({title}:{title:string})=><Text>{title}</Text>};});
jest.mock('../../../ui/BottomDrawer',()=>{const{View}=require('react-native');return{BottomDrawer:({visible,children}:{visible:boolean;children:ReactNode})=>visible?children:null,BottomDrawerScrollView:({children,...props}:{children:ReactNode})=><View {...props}>{children}</View>};});

import { KrogerCartScreen } from './KrogerCartScreen';
import { preferredGroceryStore } from '../data/preferredGroceryStore';
import { LocationPermissionService } from '../../../services/LocationPermissionService';
import { geocodeStoreSearchBestEffort, getCurrentStoreSearchContextBestEffort, hydrateStoreCoordinatesBestEffort } from '../../../services/location/currentLocation';

describe('Smiths cart flow',()=>{
 beforeEach(()=>{mockStatus.mockReset();mockConnect.mockReset().mockResolvedValue({configured:true,connection:null});mockSearchLocations.mockReset().mockResolvedValue({locations:[]});mockSelectLocation.mockReset().mockResolvedValue({});mockPrepareMatches.mockReset().mockResolvedValue({matches:[]});mockConfirmMapping.mockReset().mockResolvedValue({mappingId:'mapping-1',state:'confirmed'});mockCartAdd.mockReset().mockResolvedValue({handoffId:'handoff-1',state:'cart_add_acknowledged',cartUrl:'https://www.kroger.com/cart',addedItemCount:1,remainingItemCount:0,retailerLabel:"Smith's",replayed:false});(LocationPermissionService.syncOsPermissionStatus as jest.Mock).mockReset().mockResolvedValue('denied');(LocationPermissionService.ensurePermissionWithRationale as jest.Mock).mockReset().mockResolvedValue(false);(getCurrentStoreSearchContextBestEffort as jest.Mock).mockReset().mockResolvedValue(null);(geocodeStoreSearchBestEffort as jest.Mock).mockReset().mockResolvedValue(null);(hydrateStoreCoordinatesBestEffort as jest.Mock).mockReset().mockImplementation(async (locations:unknown[])=>locations);(preferredGroceryStore.read as jest.Mock).mockReset().mockResolvedValue(null);(preferredGroceryStore.write as jest.Mock).mockReset().mockResolvedValue(undefined);(WebBrowser.openBrowserAsync as jest.Mock).mockReset().mockResolvedValue({type:'dismiss'});});
 it('opens on a map and keeps ZIP search secondary',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByTestId('store-finder-map')).toBeTruthy();expect(screen.getByText('Stores near you')).toBeTruthy();expect(screen.queryByDisplayValue('84045')).toBeNull();expect(screen.getByRole('button',{name:'Use my current location'})).toBeTruthy();expect(screen.getByRole('button',{name:'Search stores by ZIP code'})).toBeTruthy();expect(screen.queryByText('Choose a store')).toBeNull();});
 it('renders nearby stores with only the banner and address',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:"Smith's Marketplace - Saratoga Springs Marketplace",banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Search stores by ZIP code'}));fireEvent.changeText(screen.getByLabelText('Search stores by ZIP code'),'84045');fireEvent.press(screen.getByRole('button',{name:'Find stores'}));await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84045'));expect(await screen.findByRole('button',{name:/Smith's.*689 N Redwood.*Shop with this store/i})).toBeTruthy();expect(screen.getByText("Smith's")).toBeTruthy();expect(screen.queryByText(/Saratoga Springs Marketplace/)).toBeNull();expect(screen.getByRole('button',{name:/Set Smith's as my store/})).toBeTruthy();expect(mockConnect).not.toHaveBeenCalled();});
 it('hydrates missing result coordinates so every resolvable store is represented on the map',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const unresolved={id:'70600123',name:"Smith's Marketplace - Saratoga Springs Marketplace",banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:null,longitude:null};const hydrated={...unresolved,latitude:40.353,longitude:-111.904};mockSearchLocations.mockResolvedValue({locations:[unresolved]});(hydrateStoreCoordinatesBestEffort as jest.Mock).mockResolvedValue([hydrated]);const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Search stores by ZIP code'}));fireEvent.changeText(screen.getByLabelText('Search stores by ZIP code'),'84045');fireEvent.press(screen.getByRole('button',{name:'Find stores'}));expect(await screen.findByLabelText("Smith's. 689 N Redwood Rd · Saratoga Springs, UT 84045")).toBeTruthy();expect(hydrateStoreCoordinatesBestEffort).toHaveBeenCalledWith([unresolved]);});
 it('pre-searches when current location is already available',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});(LocationPermissionService.syncOsPermissionStatus as jest.Mock).mockResolvedValue('authorized');(getCurrentStoreSearchContextBestEffort as jest.Mock).mockResolvedValue({latitude:40.34,longitude:-111.91,postalCode:'84045'});render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84045'));expect(LocationPermissionService.ensurePermissionWithRationale).not.toHaveBeenCalled();});
 it('starts product matching as soon as a store is chosen',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Search stores by ZIP code'}));fireEvent.changeText(screen.getByLabelText('Search stores by ZIP code'),'84045');fireEvent.press(screen.getByRole('button',{name:'Find stores'}));fireEvent.press(await screen.findByRole('button',{name:/Smith's.*Shop with this store/i}));await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(await screen.findByText('Cart')).toBeTruthy();expect(screen.getByRole('button',{name:"Store: Smith's. Change store"})).toBeTruthy();expect(screen.queryByText(location.address)).toBeNull();});
 it('sets a result as my store before matching the list',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Search stores by ZIP code'}));fireEvent.changeText(screen.getByLabelText('Search stores by ZIP code'),'84045');fireEvent.press(screen.getByRole('button',{name:'Find stores'}));fireEvent.press(await screen.findByRole('button',{name:/Set Smith's as my store/}));await waitFor(()=>expect(preferredGroceryStore.write).toHaveBeenCalledWith('user-1',location));await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));});
 it('remembers a preferred store and skips discovery next time',async()=>{const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockStatus.mockResolvedValue({configured:true,connection:null});(preferredGroceryStore.read as jest.Mock).mockResolvedValue(location);const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(await screen.findByText('Cart')).toBeTruthy();expect(screen.queryByTestId('store-finder-map')).toBeNull();expect(mockSearchLocations).not.toHaveBeenCalled();});

 it('renders an automatically populated cart with product imagery and hands it directly to the retailer',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const suggested={id:'p1',upc:'111',title:'Large Grade A Eggs',brand:'Kroger',size:'12 ct',thumbnailUrl:'https://images.example/eggs.png',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};const alternative={id:'p2',upc:'222',title:'Organic Brown Eggs',brand:'Simple Truth',size:'12 ct',thumbnailUrl:'https://images.example/organic-eggs.png',regularPriceCents:449,promoPriceCents:null,pickupAvailable:true};const irrelevant={id:'p3',upc:'333',title:'Chocolate Cake Mix',brand:'Kroger',size:'15 oz',thumbnailUrl:null,regularPriceCents:249,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[suggested,alternative,irrelevant]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Large Grade A Eggs')).toBeTruthy();expect(screen.getByLabelText('Large Grade A Eggs product image').props.source).toEqual({uri:'https://images.example/eggs.png'});expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByText('Estimated subtotal')).toBeTruthy();expect(screen.getAllByText('$2.99')).toHaveLength(2);expect(screen.getByTestId('kroger-cart-footer')).toBeTruthy();expect(screen.queryByText('Organic Brown Eggs')).toBeNull();fireEvent.press(screen.getByRole('button',{name:'Edit Large Grade A Eggs'}));expect(screen.queryByText('Chocolate Cake Mix')).toBeNull();fireEvent.press(await screen.findByRole('button',{name:'Use Organic Brown Eggs'}));expect(screen.queryByText('Large Grade A Eggs')).toBeNull();expect(screen.getByText('Organic Brown Eggs')).toBeTruthy();expect(mockConfirmMapping).not.toHaveBeenCalled();fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',alternative,1,expect.objectContaining({id:'store-1'})));await waitFor(()=>expect(mockCartAdd).toHaveBeenCalledWith('list-1',2));expect(await screen.findByText("Added to Smith's")).toBeTruthy();await waitFor(()=>expect(WebBrowser.openBrowserAsync).toHaveBeenCalledWith('https://www.kroger.com/cart'));});

 it('uses retailer package quantity instead of recipe measurement quantity',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const bakingPowder={id:'p1',upc:'111',title:'Baking Powder',brand:'Kroger',size:'8 oz',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'baking powder',quantity:'5',unit:'teaspoon'},products:[bakingPowder]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Qty 1')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:'Increase quantity for Baking Powder'}));expect(screen.getByText('Qty 2')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',bakingPowder,2,expect.objectContaining({id:'store-1'})));});
 it('removes a matched product from only this retailer pass',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const eggs={id:'p1',upc:'111',title:'Large Eggs',brand:'Kroger',size:'12 ct',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[eggs]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Remove Large Eggs from cart'}));expect(screen.queryByText('Large Eggs')).toBeNull();expect(screen.getByText('Your cart is empty')).toBeTruthy();expect(screen.getByText("1 grocery list item isn't in this cart.")).toBeTruthy();expect(screen.getByRole('button',{name:"Add 0 items to Smith's"}).props.accessibilityState).toEqual({disabled:true});});
 it('shows only the unavailable state when the production provider is disabled',async()=>{mockStatus.mockRejectedValue(new Error('provider_unavailable'));const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Online shopping is not configured yet. Your plain list is still available.')).toBeTruthy();expect(screen.queryByRole('button',{name:/connect/i})).toBeNull();});
 it('keeps the selected store minimal and changeable',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const selector=await screen.findByRole('button',{name:"Store: Smith's. Change store"});expect(screen.queryByText('Saratoga Springs')).toBeNull();expect(screen.queryByText('1320 Redwood Rd')).toBeNull();fireEvent.press(selector);expect(await screen.findByTestId('store-finder-map')).toBeTruthy();expect(screen.getByRole('button',{name:'Search stores by ZIP code'})).toBeTruthy();});
});
