import { fireEvent, render, waitFor } from '@testing-library/react-native';
import type { ReactNode } from 'react';
import * as WebBrowser from 'expo-web-browser';

const mockStatus=jest.fn();const mockConnect=jest.fn();const mockSearchLocations=jest.fn();const mockSelectLocation=jest.fn();const mockPrepareMatches=jest.fn();const mockConfirmMapping=jest.fn();const mockCartAdd=jest.fn();const mockList=jest.fn();
let mockBottomDrawerProps: Record<string, unknown> = {};
let mockBottomDrawerHeaderProps: Record<string, unknown> = {};
jest.mock('../data/krogerConnectionRepository',()=>({createKrogerConnectionRepository:()=>({status:mockStatus,connect:mockConnect,searchLocations:mockSearchLocations,selectLocation:mockSelectLocation,prepareMatches:mockPrepareMatches,confirmMapping:mockConfirmMapping,cartAdd:mockCartAdd})}));
jest.mock('../data/groceryRepository',()=>({createGroceryRepository:()=>({list:mockList})}));
jest.mock('../data/preferredGroceryStore',()=>({preferredGroceryStore:{read:jest.fn(),write:jest.fn(),clear:jest.fn()}}));
jest.mock('../data/retailerStoreConfirmation',()=>({retailerStoreConfirmation:{read:jest.fn(),confirm:jest.fn(),clear:jest.fn()}}));
jest.mock('../../../services/LocationPermissionService',()=>({LocationPermissionService:{syncOsPermissionStatus:jest.fn(),ensurePermissionWithRationale:jest.fn()}}));
jest.mock('../../../services/location/currentLocation',()=>({getCurrentStoreSearchContextBestEffort:jest.fn(),getStoreSearchContextForQueryBestEffort:jest.fn(),geocodeStoreSearchBestEffort:jest.fn(),hydrateStoreCoordinatesBestEffort:jest.fn(async (locations:unknown[])=>locations)}));
jest.mock('../../../store/useAppStore',()=>({useAppStore:(selector:(state:{authIdentity:{userId:string}})=>unknown)=>selector({authIdentity:{userId:'user-1'}})}));
jest.mock('expo-web-browser',()=>({openBrowserAsync:jest.fn(),maybeCompleteAuthSession:jest.fn()}));
jest.mock('react-native-maps',()=>{const React=require('react');const{Pressable,View}=require('react-native');const Map=({children,...props}:{children?:ReactNode;testID?:string})=>React.createElement(View,props,children);const Marker=({title,description,accessibilityLabel,onPress,children}:{title?:string;description?:string;accessibilityLabel?:string;onPress?:()=>void;children?:ReactNode})=>React.createElement(Pressable,{accessibilityRole:'button',accessibilityLabel:accessibilityLabel??[title,description].filter(Boolean).join('. '),onPress},children);return{__esModule:true,default:Map,Marker};});
jest.mock('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:47,right:0,bottom:24,left:0})}));
jest.mock('../../../ui/layout/AppShell',()=>({AppShell:({children}:{children:ReactNode})=>children}));
jest.mock('../../../ui/DropdownMenu',()=>{const React=require('react');const{Pressable,Text,View}=require('react-native');return{DropdownMenu:({children}:{children:ReactNode})=><>{children}</>,DropdownMenuTrigger:({children}:{children:ReactNode})=><>{children}</>,DropdownMenuContent:({children}:{children:ReactNode})=><View>{children}</View>,DropdownMenuItem:({label,onPress,disabled}:{label:string;onPress?:()=>void;disabled?:boolean})=><Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress}><Text>{label}</Text></Pressable>,DropdownMenuLabel:({children}:{children:ReactNode})=><Text>{children}</Text>,DropdownMenuSeparator:()=>null};});
jest.mock('../../../ui/layout/PageHeader',()=>{const {Text}=require('react-native');return {PageHeader:({title,rightElement}:{title:string;rightElement?:ReactNode})=><><Text>{title}</Text>{rightElement}</>};});
jest.mock('../../../ui/layout/ObjectPageHeader',()=>{const{Pressable,View}=require('react-native');return{ObjectPageHeader:({left,center,right}:{left?:ReactNode;center?:ReactNode;right?:ReactNode})=><View>{left}{center}{right}</View>,HeaderActionPill:({children,onPress,accessibilityLabel,disabled}:{children:ReactNode;onPress?:()=>void;accessibilityLabel:string;disabled?:boolean})=><Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} accessibilityState={{disabled}} disabled={disabled} onPress={onPress}>{children}</Pressable>};});
jest.mock('../../../ui/layout/BottomDrawerHeader',()=>{const{Text}=require('react-native');return{BottomDrawerHeader:(props:{title:string})=>{mockBottomDrawerHeaderProps=props;return <Text>{props.title}</Text>;}};});
jest.mock('../../../ui/BottomDrawer',()=>{const{View}=require('react-native');return{BottomDrawer:({visible,children,...props}:{visible:boolean;children:ReactNode}&Record<string,unknown>)=>{mockBottomDrawerProps=props;return visible?children:null;},BottomDrawerScrollView:({children,...props}:{children:ReactNode})=><View {...props}>{children}</View>};});

import { KrogerCartScreen } from './KrogerCartScreen';
import { preferredGroceryStore } from '../data/preferredGroceryStore';
import { retailerStoreConfirmation } from '../data/retailerStoreConfirmation';
import { LocationPermissionService } from '../../../services/LocationPermissionService';
import { geocodeStoreSearchBestEffort, getCurrentStoreSearchContextBestEffort, getStoreSearchContextForQueryBestEffort, hydrateStoreCoordinatesBestEffort } from '../../../services/location/currentLocation';

describe('Smiths cart flow',()=>{
 beforeEach(()=>{mockBottomDrawerProps={};mockBottomDrawerHeaderProps={};mockStatus.mockReset();mockConnect.mockReset().mockResolvedValue({configured:true,connection:null});mockSearchLocations.mockReset().mockResolvedValue({locations:[]});mockSelectLocation.mockReset().mockResolvedValue({});mockPrepareMatches.mockReset().mockResolvedValue({matches:[]});mockConfirmMapping.mockReset().mockResolvedValue({mappingId:'mapping-1',state:'confirmed'});mockCartAdd.mockReset().mockResolvedValue({handoffId:'handoff-1',state:'cart_add_acknowledged',cartUrl:'https://www.kroger.com/cart',addedItemCount:1,remainingItemCount:0,retailerLabel:"Smith's",replayed:false});(retailerStoreConfirmation.read as jest.Mock).mockReset().mockResolvedValue({authority:'user_confirmed',locationId:'store-1'});(retailerStoreConfirmation.confirm as jest.Mock).mockReset().mockResolvedValue({authority:'user_confirmed',locationId:'store-1'});(retailerStoreConfirmation.clear as jest.Mock).mockReset().mockResolvedValue(undefined);mockList.mockReset().mockResolvedValue([{id:'list-1',revision:2,status:'ready',sourceKind:'meal_plan',sourceMealPlanId:'plan-1',sourceMealPlanVersion:1,sourceRecipeVersionId:null,sourceTitle:null,updatedAt:'2026-08-10T12:00:00.000Z',items:[{id:'one',concept:'eggs',state:'needed',retailerCart:null},{id:'two',concept:'butter',state:'needed',retailerCart:null}]}]);(LocationPermissionService.syncOsPermissionStatus as jest.Mock).mockReset().mockResolvedValue('denied');(LocationPermissionService.ensurePermissionWithRationale as jest.Mock).mockReset().mockResolvedValue(false);(getCurrentStoreSearchContextBestEffort as jest.Mock).mockReset().mockResolvedValue(null);(getStoreSearchContextForQueryBestEffort as jest.Mock).mockReset().mockResolvedValue(null);(geocodeStoreSearchBestEffort as jest.Mock).mockReset().mockResolvedValue(null);(hydrateStoreCoordinatesBestEffort as jest.Mock).mockReset().mockImplementation(async (locations:unknown[])=>locations);(preferredGroceryStore.read as jest.Mock).mockReset().mockResolvedValue(null);(preferredGroceryStore.write as jest.Mock).mockReset().mockResolvedValue(undefined);(preferredGroceryStore.clear as jest.Mock).mockReset().mockResolvedValue(undefined);(WebBrowser.openBrowserAsync as jest.Mock).mockReset().mockResolvedValue({type:'dismiss'});});
 it('opens as a full-bleed map with floating navigation and one area search field',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByTestId('store-finder-map')).toBeTruthy();expect(screen.getByText('Nearby stores')).toBeTruthy();expect(screen.getByLabelText('Search for nearby stores')).toBeTruthy();expect(screen.getByPlaceholderText('City, address, or ZIP')).toBeTruthy();expect(screen.getByRole('button',{name:'Back to groceries'})).toBeTruthy();expect(screen.getByRole('button',{name:'Use my current location'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Find stores'})).toBeNull();expect(screen.queryByText('Shop online')).toBeNull();});
 it('keeps the map drawer user-draggable and extends its surface through the bottom safe area',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);await screen.findByTestId('store-finder-map');expect(mockBottomDrawerProps.initialSnapIndex).toBe(0);expect(mockBottomDrawerProps.snapIndex).toBeUndefined();expect(mockBottomDrawerProps.enableContentPanningGesture).toBe(true);expect(mockBottomDrawerProps.contentExtendsIntoBottomSafeArea).toBe(true);expect(mockBottomDrawerProps.handleContainerStyle).toEqual(expect.objectContaining({paddingTop:8,paddingBottom:4}));expect(mockBottomDrawerHeaderProps.containerStyle).toEqual(expect.objectContaining({paddingBottom:4}));});
 it('resolves an address to a retailer search area',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});(getStoreSearchContextForQueryBestEffort as jest.Mock).mockResolvedValue({latitude:40.3916,longitude:-111.8508,postalCode:'84043'});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'Lehi, UT');fireEvent(search,'submitEditing');await waitFor(()=>expect(getStoreSearchContextForQueryBestEffort).toHaveBeenCalledWith('Lehi, UT'));await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84043'));});
 it('renders nearby stores with only the banner and a two-line address',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:"Smith's Marketplace - Saratoga Springs Marketplace",banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'84045');fireEvent(search,'submitEditing');await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84045'));expect(await screen.findByRole('button',{name:/Smith's.*689 N Redwood.*Shop with this store/i})).toBeTruthy();const address=screen.getByText(location.address);expect(address.props.numberOfLines).toBe(2);expect(address).toHaveStyle({fontSize:12,lineHeight:16});expect(screen.getByText("Smith's")).toBeTruthy();expect(screen.queryByText(/Saratoga Springs Marketplace/)).toBeNull();expect(screen.getByRole('button',{name:/Set Smith's as my store/})).toBeTruthy();expect(mockConnect).not.toHaveBeenCalled();});
 it('hydrates missing result coordinates so every resolvable store is represented on the map',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const unresolved={id:'70600123',name:"Smith's Marketplace - Saratoga Springs Marketplace",banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:null,longitude:null};const hydrated={...unresolved,latitude:40.353,longitude:-111.904};mockSearchLocations.mockResolvedValue({locations:[unresolved]});(hydrateStoreCoordinatesBestEffort as jest.Mock).mockResolvedValue([hydrated]);const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'84045');fireEvent(search,'submitEditing');expect(await screen.findByLabelText("A. Smith's. 689 N Redwood Rd · Saratoga Springs, UT 84045")).toBeTruthy();expect(hydrateStoreCoordinatesBestEffort).toHaveBeenCalledWith([unresolved]);});
 it('keeps map letters attached to stores when a marker brings its row forward',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const first={id:'one',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};const second={id:'two',name:'Maceys',banner:"Macey's",address:'760 E Main St · Lehi, UT 84043',latitude:40.39,longitude:-111.84};mockSearchLocations.mockResolvedValue({locations:[first,second]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'84045');fireEvent(search,'submitEditing');fireEvent.press(await screen.findByRole('button',{name:"B. Macey's. 760 E Main St · Lehi, UT 84043"}));expect(screen.getByRole('button',{name:/B.*Macey's.*Shop with this store/i}).props.accessibilityState).toEqual({selected:true});expect(mockPrepareMatches).not.toHaveBeenCalled();});
 it('pre-searches when current location is already available',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});(LocationPermissionService.syncOsPermissionStatus as jest.Mock).mockResolvedValue('authorized');(getCurrentStoreSearchContextBestEffort as jest.Mock).mockResolvedValue({latitude:40.34,longitude:-111.91,postalCode:'84045'});render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84045'));expect(LocationPermissionService.ensurePermissionWithRationale).not.toHaveBeenCalled();});
 it('starts product matching and invalidates prior confirmation as soon as a store is chosen',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'84045');fireEvent(search,'submitEditing');fireEvent.press(await screen.findByRole('button',{name:/Smith's.*Shop with this store/i}));await waitFor(()=>expect(retailerStoreConfirmation.clear).toHaveBeenCalledWith('user-1'));await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(screen.getByRole('button',{name:`Change store. Current store Smith's, ${location.address}`})).toBeTruthy();expect(screen.getAllByText(location.address).length).toBeGreaterThan(0);});
 it('remembers a store without starting product matching',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockSearchLocations.mockResolvedValue({locations:[location]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const search=await screen.findByLabelText('Search for nearby stores');fireEvent.changeText(search,'84045');fireEvent(search,'submitEditing');fireEvent.press(await screen.findByRole('button',{name:/Set Smith's as my store/}));await waitFor(()=>expect(preferredGroceryStore.write).toHaveBeenCalledWith('user-1',location));expect(mockPrepareMatches).not.toHaveBeenCalled();expect(screen.getByTestId('store-finder-map')).toBeTruthy();expect(screen.getByRole('button',{name:"Smith's is my store"})).toBeTruthy();});
 it('shows cart loading instead of the map until a preferred-store cart is populated',async()=>{const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockStatus.mockResolvedValue({configured:true,connection:null});(preferredGroceryStore.read as jest.Mock).mockResolvedValue(location);mockPrepareMatches.mockReturnValue(new Promise(()=>undefined));const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(screen.getByTestId('kroger-cart-loading')).toBeTruthy();expect(screen.getByText('Building your cart')).toBeTruthy();expect(screen.queryByTestId('store-finder-map')).toBeNull();await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(screen.getByTestId('kroger-cart-loading')).toBeTruthy();expect(screen.queryByTestId('store-finder-map')).toBeNull();});
 it('remembers a preferred store and skips discovery next time',async()=>{const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045',latitude:40.34,longitude:-111.91};mockStatus.mockResolvedValue({configured:true,connection:null});(preferredGroceryStore.read as jest.Mock).mockResolvedValue(location);const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(screen.getByRole('button',{name:`Change store. Current store Smith's, ${location.address}`})).toBeTruthy();expect(screen.queryByTestId('store-finder-map')).toBeNull();expect(mockSearchLocations).not.toHaveBeenCalled();});

 it('holds the Smiths cart in Kwilt until the pickup store is confirmed',async()=>{
  mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});
  (retailerStoreConfirmation.read as jest.Mock).mockResolvedValue(null);
  mockCartAdd.mockResolvedValue({handoffId:'handoff-1',state:'cart_add_acknowledged',cartUrl:'https://www.smithsfoodanddrug.com/cart',addedItemCount:1,remainingItemCount:0,retailerLabel:"Smith's",replayed:false});
  const suggested={id:'p1',upc:'111',title:'Large Grade A Eggs',brand:'Kroger',size:'12 ct',thumbnailUrl:'https://images.example/eggs.png',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};
  const alternative={id:'p2',upc:'222',title:'Organic Brown Eggs',brand:'Simple Truth',size:'12 ct',thumbnailUrl:'https://images.example/organic-eggs.png',regularPriceCents:449,promoPriceCents:null,pickupAvailable:true};
  mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[suggested,alternative]}]});
  const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);
  expect(await screen.findByText('Large Grade A Eggs')).toBeTruthy();
  fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));
  await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',suggested,1,expect.objectContaining({id:'store-1'})));
  expect(await screen.findByText('Confirm pickup store')).toBeTruthy();
  expect(screen.getByText("Before Kwilt adds anything, set Smith's pickup to 1320 Redwood Rd.")).toBeTruthy();
  expect(mockCartAdd).not.toHaveBeenCalled();
  expect(WebBrowser.openBrowserAsync).not.toHaveBeenCalled();
  fireEvent.press(screen.getByRole('button',{name:"Set pickup store at Smith's"}));
  expect(WebBrowser.openBrowserAsync).toHaveBeenCalledWith('https://www.smithsfoodanddrug.com/cart');
  expect(await screen.findByText("Is Smith's pickup set to 1320 Redwood Rd?")).toBeTruthy();
  fireEvent.press(screen.getByRole('button',{name:'Yes, add 1 item'}));
  await waitFor(()=>expect(retailerStoreConfirmation.confirm).toHaveBeenCalledWith('user-1',expect.objectContaining({id:'store-1'})));
  await waitFor(()=>expect(mockCartAdd).toHaveBeenCalledWith('list-1',2,expect.objectContaining({id:'store-1'})));
  expect(await screen.findByText('Added to Saratoga Springs')).toBeTruthy();
 });

 it('uses a remembered exact-store confirmation without repeating the retailer round trip',async()=>{
  mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:'QFC',location:{id:'seattle-1',name:'University Village',address:'2746 NE 45th St · Seattle, WA 98105'},capabilities:{productMatch:true,cartAdd:true}}});
  const eggs={id:'p1',upc:'111',title:'Large Eggs',brand:'Kroger',size:'12 ct',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};
  mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[eggs]}]});
  const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);
  fireEvent.press(await screen.findByRole('button',{name:'Add 1 item to QFC'}));
  await waitFor(()=>expect(mockCartAdd).toHaveBeenCalledWith('list-1',2,expect.objectContaining({id:'seattle-1'})));
  expect(WebBrowser.openBrowserAsync).not.toHaveBeenCalled();
  expect(retailerStoreConfirmation.confirm).not.toHaveBeenCalled();
 });

 it('opens product alternatives from the row and immediately updates the draft price',async()=>{
  mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});
  const suggested={id:'p1',upc:'111',title:'Large Grade A Eggs',brand:'Kroger',size:'12 ct',thumbnailUrl:'https://images.example/eggs.png',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};
  const alternative={id:'p2',upc:'222',title:'Simple Truth Brown Eggs',brand:'Simple Truth',size:'12 ct',thumbnailUrl:'https://images.example/brown-eggs.png',regularPriceCents:349,promoPriceCents:229,pickupAvailable:true};
  mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[suggested,alternative]}]});
  const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);

  fireEvent.press(await screen.findByRole('button',{name:'Compare alternatives for Large Grade A Eggs'}));
  expect(screen.getByText('Choose eggs')).toBeTruthy();
  expect(mockBottomDrawerHeaderProps.subtitle).toBe("2 options at Smith's");
  expect(screen.getByRole('button',{name:'Select Large Grade A Eggs, 12 ct, $2.99'}).props.accessibilityState).toEqual({selected:true});
  expect(screen.getByText('Sale')).toBeTruthy();
  expect(screen.getByText('$3.49')).toHaveStyle({textDecorationLine:'line-through'});

  fireEvent.press(screen.getByRole('button',{name:'Select Simple Truth Brown Eggs, 12 ct, sale price $2.29, regular price $3.49'}));
  expect(screen.queryByText('Choose eggs')).toBeNull();
  expect(screen.getByText('Simple Truth Brown Eggs')).toBeTruthy();
  expect(screen.getAllByText('$2.29')).toHaveLength(2);

  fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));
  await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',alternative,1,expect.objectContaining({id:'store-1'})));
 });

 it('uses retailer package quantity instead of recipe measurement quantity',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const bakingPowder={id:'p1',upc:'111',title:'Baking Powder',brand:'Kroger',size:'8 oz',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'baking powder',quantity:'5',unit:'teaspoon'},products:[bakingPowder]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Qty 1')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:'Increase quantity for Baking Powder'}));expect(screen.getByText('Qty 2')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:"Add 2 items to Smith's"}));await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',bakingPowder,2,expect.objectContaining({id:'store-1'})));});
 it('consolidates two grocery needs that resolve to the same retailer product',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const butter={id:'p1',upc:'111',title:'Kroger Unsalted Butter Sticks',brand:'Kroger',size:'4 sticks / 16 oz',regularPriceCents:349,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'unsalted butter',quantity:'1',unit:'cup'},products:[butter]},{groceryItem:{id:'two',concept:'butter',quantity:'4',unit:'tablespoon'},products:[butter]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findAllByText('Kroger Unsalted Butter Sticks')).toHaveLength(1);expect(screen.getByText('Qty 2')).toBeTruthy();expect(screen.getByRole('button',{name:"Add 2 items to Smith's"})).toBeTruthy();});
 it('teaches that already-have items are checked off in the grocery list',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const eggs={id:'p1',upc:'111',title:'Large Eggs',brand:'Kroger',size:'12 ct',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[eggs]}]});const goBack=jest.fn();const screen=render(<KrogerCartScreen navigation={{goBack} as never} route={{params:{listId:'list-1'}} as never}/>);const hint=await screen.findByRole('button',{name:'Already have something? Check it off in your grocery list'});expect(hint.props.accessibilityHint).toBe('Returns to your grocery list.');fireEvent.press(hint);expect(goBack).toHaveBeenCalledTimes(1);});
 it('keeps subtotal caveats behind info and lifts the footer above content',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const footer=await screen.findByTestId('kroger-cart-footer');expect(screen.getByRole('button',{name:'About estimated subtotal'})).toBeTruthy();expect(screen.queryByText(/Current item prices at/)).toBeNull();expect(screen.queryByText(/Then review pickup/)).toBeNull();expect(footer).toHaveStyle({shadowOffset:{width:0,height:-4}});});
 it('removes a matched product from only this retailer pass',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const eggs={id:'p1',upc:'111',title:'Large Eggs',brand:'Kroger',size:'12 ct',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[eggs]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Remove Large Eggs from this cart'}));expect(screen.queryByText('Large Eggs')).toBeNull();expect(screen.getByText('Your cart is empty')).toBeTruthy();expect(screen.getByText("1 grocery list item isn't in this cart.")).toBeTruthy();expect(screen.getByRole('button',{name:"Add 0 items to Smith's"}).props.accessibilityState).toEqual({disabled:true});});
 it('shows only the unavailable state when the production provider is disabled',async()=>{mockStatus.mockRejectedValue(new Error('provider_unavailable'));const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Online shopping is not configured yet. Your plain list is still available.')).toBeTruthy();expect(screen.queryByRole('button',{name:/connect/i})).toBeNull();});
 it('keeps the selected store in one compact fixed header through the top safe area',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByRole('button',{name:"Change store. Current store Smith's, 1320 Redwood Rd"})).toBeTruthy();expect(screen.getByTestId('store-menu-trigger')).toBeTruthy();expect(screen.queryByText('Change store')).toBeNull();expect(screen.getAllByText('1320 Redwood Rd')).toHaveLength(1);expect(screen.getByText('1320 Redwood Rd')).toHaveStyle({fontSize:11,lineHeight:14});expect(screen.getByTestId('kroger-cart-header')).toHaveStyle({minHeight:99,marginTop:-47,marginHorizontal:-8,paddingTop:51,shadowOffset:{width:0,height:4}});fireEvent.press(screen.getByRole('button',{name:'Choose another store'}));expect(await screen.findByTestId('store-finder-map')).toBeTruthy();expect(screen.getByLabelText('Search for nearby stores')).toBeTruthy();});
});
