import { fireEvent, render, waitFor } from '@testing-library/react-native';
import type { ReactNode } from 'react';
import * as WebBrowser from 'expo-web-browser';

const mockStatus=jest.fn();const mockConnect=jest.fn();const mockSearchLocations=jest.fn();const mockSelectLocation=jest.fn();const mockPrepareMatches=jest.fn();const mockConfirmMapping=jest.fn();const mockCartAdd=jest.fn();
jest.mock('../data/krogerConnectionRepository',()=>({createKrogerConnectionRepository:()=>({status:mockStatus,connect:mockConnect,searchLocations:mockSearchLocations,selectLocation:mockSelectLocation,prepareMatches:mockPrepareMatches,confirmMapping:mockConfirmMapping,cartAdd:mockCartAdd})}));
jest.mock('../data/groceryRepository',()=>({createGroceryRepository:()=>({list:jest.fn().mockResolvedValue([{id:'list-1',revision:2,status:'ready',items:[{id:'one',state:'needed',retailerCart:null},{id:'two',state:'needed',retailerCart:null}]}])})}));
jest.mock('expo-web-browser',()=>({openBrowserAsync:jest.fn()}));
jest.mock('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,right:0,bottom:24,left:0})}));
jest.mock('../../../ui/layout/AppShell',()=>({AppShell:({children}:{children:ReactNode})=>children}));
jest.mock('../../../ui/layout/PageHeader',()=>{const {Text}=require('react-native');return {PageHeader:({title,rightElement}:{title:string;rightElement?:ReactNode})=><><Text>{title}</Text>{rightElement}</>};});

import { KrogerCartScreen } from './KrogerCartScreen';

describe('Smiths cart flow',()=>{
 beforeEach(()=>{mockStatus.mockReset();mockConnect.mockReset().mockResolvedValue({configured:true,connection:null});mockSearchLocations.mockReset().mockResolvedValue({locations:[]});mockSelectLocation.mockReset().mockResolvedValue({});mockPrepareMatches.mockReset().mockResolvedValue({matches:[]});mockConfirmMapping.mockReset().mockResolvedValue({mappingId:'mapping-1',state:'confirmed'});mockCartAdd.mockReset().mockResolvedValue({handoffId:'handoff-1',state:'cart_add_acknowledged',cartUrl:'https://www.kroger.com/cart',addedItemCount:1,remainingItemCount:0,retailerLabel:"Smith's",replayed:false});(WebBrowser.openBrowserAsync as jest.Mock).mockReset().mockResolvedValue({type:'dismiss'});});
 it('uses the Shop online header as the only store-picker introduction',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByDisplayValue('84045')).toBeTruthy();expect(screen.queryByText('Choose a store')).toBeNull();expect(screen.queryByText(/Products, prices, and pickup availability/)).toBeNull();expect(screen.queryByRole('button',{name:/connect/i})).toBeNull();});
 it('renders nearby Kroger-family stores before account connection',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});mockSearchLocations.mockResolvedValue({locations:[{id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045'}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByDisplayValue('84045')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:'Find stores'}));await waitFor(()=>expect(mockSearchLocations).toHaveBeenCalledWith('84045'));expect(await screen.findByRole('button',{name:/Smiths.*689 N Redwood/i})).toBeTruthy();expect(mockConnect).not.toHaveBeenCalled();});
 it('starts product matching as soon as a store is chosen',async()=>{mockStatus.mockResolvedValue({configured:true,connection:null});const location={id:'70600123',name:'Smiths',banner:"Smith's",address:'689 N Redwood Rd · Saratoga Springs, UT 84045'};mockSearchLocations.mockResolvedValue({locations:[location]});mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Find stores'}));fireEvent.press(await screen.findByRole('button',{name:/Smiths.*689 N Redwood/i}));await waitFor(()=>expect(mockPrepareMatches).toHaveBeenCalledWith('list-1',2,location));expect(await screen.findByText('Cart')).toBeTruthy();expect(screen.queryByText('Choose products')).toBeNull();expect(screen.queryByText('Match your list')).toBeNull();expect(screen.getByRole('button',{name:"Store: Smith's. Change store"})).toBeTruthy();expect(screen.queryByText(location.address)).toBeNull();});

 it('renders an automatically populated cart with product imagery and hands it directly to the retailer',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const suggested={id:'p1',upc:'111',title:'Large Grade A Eggs',brand:'Kroger',size:'12 ct',thumbnailUrl:'https://images.example/eggs.png',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};const alternative={id:'p2',upc:'222',title:'Organic Brown Eggs',brand:'Simple Truth',size:'12 ct',thumbnailUrl:'https://images.example/organic-eggs.png',regularPriceCents:449,promoPriceCents:null,pickupAvailable:true};const irrelevant={id:'p3',upc:'333',title:'Chocolate Cake Mix',brand:'Kroger',size:'15 oz',thumbnailUrl:null,regularPriceCents:249,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[suggested,alternative,irrelevant]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Large Grade A Eggs')).toBeTruthy();expect(screen.getByLabelText('Large Grade A Eggs product image').props.source).toEqual({uri:'https://images.example/eggs.png'});expect(screen.queryByRole('radio')).toBeNull();expect(screen.getByText('Estimated subtotal')).toBeTruthy();expect(screen.getAllByText('$2.99')).toHaveLength(2);expect(screen.getByTestId('kroger-cart-footer')).toBeTruthy();expect(screen.queryByText('Organic Brown Eggs')).toBeNull();fireEvent.press(screen.getByRole('button',{name:'Edit Large Grade A Eggs'}));expect(screen.queryByText('Chocolate Cake Mix')).toBeNull();fireEvent.press(await screen.findByRole('button',{name:'Use Organic Brown Eggs'}));expect(screen.queryByText('Large Grade A Eggs')).toBeNull();expect(screen.getByText('Organic Brown Eggs')).toBeTruthy();expect(mockConfirmMapping).not.toHaveBeenCalled();fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',alternative,1,expect.objectContaining({id:'store-1'})));await waitFor(()=>expect(mockCartAdd).toHaveBeenCalledWith('list-1',2));expect(await screen.findByText("Added to Smith's")).toBeTruthy();await waitFor(()=>expect(WebBrowser.openBrowserAsync).toHaveBeenCalledWith('https://www.kroger.com/cart'));});

 it('uses retailer package quantity instead of recipe measurement quantity',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const bakingPowder={id:'p1',upc:'111',title:'Baking Powder',brand:'Kroger',size:'8 oz',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'baking powder',quantity:'5',unit:'teaspoon'},products:[bakingPowder]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Qty 1')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:'Increase quantity for Baking Powder'}));expect(screen.getByText('Qty 2')).toBeTruthy();fireEvent.press(screen.getByRole('button',{name:"Add 1 item to Smith's"}));await waitFor(()=>expect(mockConfirmMapping).toHaveBeenCalledWith('list-1','one',bakingPowder,2,expect.objectContaining({id:'store-1'})));});
 it('removes a matched product from only this retailer pass',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const eggs={id:'p1',upc:'111',title:'Large Eggs',brand:'Kroger',size:'12 ct',regularPriceCents:299,promoPriceCents:null,pickupAvailable:true};mockPrepareMatches.mockResolvedValue({matches:[{groceryItem:{id:'one',concept:'eggs',quantity:'6',unit:'count'},products:[eggs]}]});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);fireEvent.press(await screen.findByRole('button',{name:'Remove Large Eggs from cart'}));expect(screen.queryByText('Large Eggs')).toBeNull();expect(screen.getByText('Your cart is empty')).toBeTruthy();expect(screen.getByText("1 grocery list item isn't in this cart.")).toBeTruthy();expect(screen.getByRole('button',{name:"Add 0 items to Smith's"}).props.accessibilityState).toEqual({disabled:true});});
 it('shows only the unavailable state when the production provider is disabled',async()=>{mockStatus.mockRejectedValue(new Error('provider_unavailable'));const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);expect(await screen.findByText('Online shopping is not configured yet. Your plain list is still available.')).toBeTruthy();expect(screen.queryByRole('button',{name:/connect/i})).toBeNull();});
 it('keeps the selected store minimal and changeable',async()=>{mockStatus.mockResolvedValue({configured:true,connection:{state:'active',retailerLabel:"Smith's",location:{id:'store-1',name:'Saratoga Springs',address:'1320 Redwood Rd'},capabilities:{productMatch:true,cartAdd:true}}});const screen=render(<KrogerCartScreen navigation={{goBack:jest.fn()} as never} route={{params:{listId:'list-1'}} as never}/>);const selector=await screen.findByRole('button',{name:"Store: Smith's. Change store"});expect(screen.queryByText('Saratoga Springs')).toBeNull();expect(screen.queryByText('1320 Redwood Rd')).toBeNull();fireEvent.press(selector);expect(await screen.findByDisplayValue('84045')).toBeTruthy();});
});
