import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { buildVerificationPlan } from './plan.mjs';

// Captured from the original CLI before extraction, not regenerated by this test.
const fixtures = JSON.parse(fs.readFileSync(new URL('./fixtures/protected-plans.json', import.meta.url)));
for (const { name, files, expected } of fixtures) {
  test(`protected gate selection remains identical: ${name}`, () => {
    assert.deepEqual(buildVerificationPlan(files, 'origin/main'), expected);
  });
}

test('verification tooling changes add self-tests without replacing existing checks', () => {
  const plan = buildVerificationPlan(['scripts/verification/local-runner.mjs'], 'origin/main');
  assert.deepEqual(plan.commands.map(c => c.command), [
    'git diff --check',
    'npm run code:health -- --fail-on-regression --base "origin/main"',
    'npm run test:verification',
  ]);
});

for (const file of [
  'scripts/input-patterns/scan.mjs',
  'scripts/input-patterns/baseline.json',
  'src/capabilities/money/screens/MoneyEditScreen.tsx',
  'src/components/AnotherInput.tsx',
  'src/theme/colors.ts',
  'packages/arc-survey/src/Question.tsx',
  'packages/kwilt-tokens/src/colors.ts',
  'package.json',
]) {
  test(`PR verification enforces the input policy when ${file} changes alone`, () => {
    const plan = buildVerificationPlan([file], 'origin/main');
    assert(plan.commands.some(entry => entry.command === 'npm run architecture:lint'));
  });
}
