import { StyleSheet } from "react-native";

import { colors, fonts, radii, spacing, typography } from "../../../theme";
import {
  RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
  RESTING_COMPOSER_HEIGHT_PX,
  RESTING_COMPOSER_HORIZONTAL_INSET_PX,
} from "../../../ui/layout/restingComposerMetrics";

const recipeCanvasHorizontalInset = spacing.sm + spacing.md;

export const styles = StyleSheet.create({
  list: {
    paddingHorizontal: recipeCanvasHorizontalInset,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.sm,
  },
  libraryHeader: {
    gap: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  discoveryList: {
    paddingHorizontal: recipeCanvasHorizontalInset,
    paddingTop: spacing.xs,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.lg,
  },
  discoveryHeader: { gap: spacing.lg },
  inventoryControls: { gap: spacing.sm },
  appShellHeaderInset: { paddingHorizontal: spacing.sm },
  discoveryNavigation: { gap: spacing.md },
  controlRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  resultCount: { marginLeft: "auto", flexShrink: 0 },
  menuItemRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  mealsMenuContent: { width: 276, minWidth: 276 },
  menuServingRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  menuServingLabel: { flex: 1, minWidth: 0 },
  menuServingControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  menuServingButton: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuServingButtonDisabled: { opacity: 0.4 },
  menuServingButtonLabel: { ...typography.titleSm, lineHeight: 22 },
  menuServingCount: { ...typography.body, minWidth: 16, textAlign: "center" },
  mealPlanHeaderAction: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    backgroundColor: colors.fieldFill,
  },
  mealPlanHeaderLabel: { color: colors.textPrimary },
  mealPlanCountBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 5,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.sumi900,
  },
  mealPlanCountText: {
    color: colors.primaryForeground,
    fontSize: 10,
    lineHeight: 12,
  },
  quickFilterRail: {
    marginTop: -spacing.xs,
    marginHorizontal: -recipeCanvasHorizontalInset,
  },
  quickFilterRow: {
    gap: spacing.xs,
    paddingHorizontal: recipeCanvasHorizontalInset,
  },
  quickFilter: {
    height: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.canvas,
  },
  quickFilterSelected: {
    borderColor: colors.sumi900,
    backgroundColor: colors.sumi900,
  },
  quickFilterTextSelected: { color: colors.primaryForeground },
  edgeToEdgeRail: { marginHorizontal: -recipeCanvasHorizontalInset },
  cuisineRow: {
    gap: spacing.sm,
    paddingHorizontal: recipeCanvasHorizontalInset,
    paddingRight: spacing.xl,
  },
  cuisineCard: { width: 88, alignItems: "center", gap: spacing.xs },
  cuisineCardPressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  cuisineAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    overflow: "hidden",
  },
  cuisineArtwork: {
    width: "100%",
    height: "100%",
    borderRadius: 34,
  },
  cuisineLabel: { textAlign: "center", fontSize: 10, lineHeight: 13 },
  editorialOffer: {
    width: "100%",
    height: 104,
    overflow: "hidden",
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  editorialOfferPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },
  editorialOfferArtwork: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  editorialOfferShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(28,26,25,0.48)",
  },
  editorialOfferCopy: {
    position: "absolute",
    top: spacing.sm,
    bottom: spacing.sm,
    left: spacing.md,
    zIndex: 2,
    width: 184,
    justifyContent: "center",
    gap: spacing.xs,
  },
  editorialOfferEyebrow: {
    color: colors.primaryForeground,
    fontSize: 10,
    letterSpacing: 0.8,
  },
  editorialOfferTitle: { color: colors.primaryForeground },
  editorialOfferAction: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: spacing.xs,
  },
  editorialOfferActionText: { color: colors.primaryForeground },
  gridRow: { gap: spacing.sm },
  card: { flex: 1, minWidth: 0, marginBottom: spacing.md },
  shelfCard: { flex: 0, width: 164, marginBottom: 0 },
  cardArtworkFrame: { position: "relative" },
  cardArtwork: { width: "100%", aspectRatio: 1.15, borderRadius: 18 },
  planCardToggle: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
  },
  planCardToggleSelected: { backgroundColor: colors.sumi900 },
  cardBody: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.xs,
    gap: spacing.xs,
  },
  cardTitle: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 15,
    lineHeight: 19,
  },
  cardMeta: { ...typography.bodyXs },
  recommendationReason: {
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
  },
  recommendationReasonText: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
  },
  shelf: { gap: spacing.sm },
  shelfHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  seeAll: {
    minHeight: 44,
    minWidth: 64,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingLeft: spacing.sm,
  },
  seeAllText: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 14,
    lineHeight: 20,
  },
  shelfContent: {
    gap: spacing.sm,
    paddingHorizontal: recipeCanvasHorizontalInset,
  },
  pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] },
  empty: {
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.xl * 2,
    paddingHorizontal: spacing.md,
  },
  drawerContent: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  filterSection: { gap: spacing.sm },
  filterProgress: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: -spacing.sm,
  },
  choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  filterChoice: {
    minHeight: 38,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: colors.canvas,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChoiceSelected: {
    backgroundColor: colors.sumi900,
    borderColor: colors.sumi900,
  },
  filterChoiceTextSelected: { color: colors.canvas },
  optionRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  optionCopy: { flex: 1, minWidth: 0, gap: 2 },
  optionSelected: {
    fontFamily: typography.titleSm.fontFamily,
    color: colors.accent,
  },
  captureRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  captureIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary,
  },
  dock: {
    position: "absolute",
    left: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    right: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    bottom: RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
    height: RESTING_COMPOSER_HEIGHT_PX,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 60,
    elevation: 60,
  },
  primaryDockButton: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  primaryDockSurface: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  primaryDockSurfaceContent: {
    height: RESTING_COMPOSER_HEIGHT_PX,
    justifyContent: "center",
  },
  primaryDockContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  planDrawerSheet: {
    paddingHorizontal: 0,
    paddingTop: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  planDrawerHandleRegion: { paddingTop: spacing.sm, paddingBottom: spacing.xs },
  planDrawerViewport: { flex: 1, minHeight: 0, overflow: "hidden" },
  planDrawerHeader: {
    minHeight: 76,
    paddingHorizontal: spacing.lg,
    justifyContent: "center",
  },
  planDrawerHeaderMain: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planDrawerTitleIdentity: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planDrawerShareActionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planGuestSuggestions: {
    gap: spacing.xs,
    paddingTop: spacing.sm,
  },
  planDrawerContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl * 2,
  },
  committedPlanSection: { gap: spacing.md, paddingBottom: spacing.sm },
  committedPlanHeading: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: spacing.md },
  committedMealList: { gap: spacing.sm },
  committedMealCard: {
    minHeight: 96,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  committedMealArtwork: { width: 64, height: 64, borderRadius: 14 },
  committedMealCopy: { flex: 1, minWidth: 0, gap: 2 },
  committedMealTitle: { ...typography.titleSm, minWidth: 0 },
  planDrawerList: { gap: spacing.sm },
  planDrawerItem: {},
  planDrawerRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  planMoveHandle: {
    width: 30,
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.control,
    marginLeft: -spacing.xs,
  },
  planDragMealCell: {
    minHeight: 64,
    marginBottom: spacing.sm,
    paddingVertical: 4,
    paddingHorizontal: spacing.xs,
    marginHorizontal: -spacing.xs,
    borderRadius: radii.control,
  },
  planDragMealCellActive: {
    backgroundColor: colors.canvas,
  },
  planGetIdeasRow: {
    minHeight: 48,
    justifyContent: "center",
    marginBottom: spacing.xs,
  },
  planGetIdeasOffer: {
    minHeight: 48,
    alignItems: "flex-start",
    borderRadius: radii.card,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: colors.shellAlt,
  },
  planGetIdeasContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planDragSectionActive: {
    backgroundColor: colors.fieldFill,
  },
  planDrawerSelection: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  planDrawerSelectionActive: { backgroundColor: colors.sumi900, borderColor: colors.sumi900 },
  planDrawerArtworkFrame: {
    width: 56,
    height: 56,
    flexShrink: 0,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: colors.secondary,
  },
  planDrawerArtwork: { width: 56, height: 56, borderRadius: 14 },
  planDrawerMealCopy: { flex: 1, minWidth: 0, gap: 2 },
  planDrawerTitle: { ...typography.body, minWidth: 0, fontFamily: fonts.semibold, fontSize: 15, lineHeight: 22 },
  planDrawerMore: { alignSelf: "flex-start", marginTop: -6, flexShrink: 0 },
  planPeopleTrigger: { minHeight: 32, alignSelf: "flex-start", justifyContent: "center", borderRadius: 999, paddingHorizontal: spacing.xs },
  planPeopleMenu: { width: 240, gap: 2 },
  planReactionBar: { minWidth: 0, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 4 },
  planReactionPill: { minHeight: 32, alignItems: "center", justifyContent: "center", borderRadius: 999, borderWidth: 1, paddingHorizontal: spacing.sm },
  planReactionPillIdle: { backgroundColor: colors.canvas, borderColor: colors.border },
  planReactionPillSelected: { backgroundColor: colors.secondary, borderColor: colors.border },
  planReactionPillContent: { flexDirection: "row", alignItems: "center", gap: 4 },
  planReactionEmoji: { fontSize: 16, lineHeight: 22, transform: [{ translateY: 1 }] },
  planResponseAction: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderRadius: 999, backgroundColor: colors.secondary },
  planReactionDrawerContent: {
    flex: 1,
    minHeight: 0,
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  planReactionState: { flex: 1, minHeight: 0 },
  planReactionPickerScrollContent: { gap: spacing.md, paddingBottom: spacing.lg },
  planReactionSection: { gap: spacing.xs },
  planReactionChoices: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  planHardPassSection: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border, paddingTop: spacing.md, gap: spacing.xs },
  planReactionChoice: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: radii.pill, borderWidth: 2, borderColor: "transparent", backgroundColor: colors.fieldFill },
  planReactionChoiceSelected: { borderColor: colors.textPrimary, backgroundColor: colors.secondary },
  planReactionChoiceCheck: { position: "absolute", top: -4, right: -4, width: 18, height: 18, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: colors.textPrimary, borderWidth: 2, borderColor: colors.card },
  planReactionChoiceEmoji: { fontSize: 27, lineHeight: 34 },
  planHardPassComposerContent: { paddingBottom: spacing.md },
  planHardPassField: { gap: spacing.xs },
  planHardPassReasonHeader: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  planHardPassSelectedPill: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.textPrimary,
    backgroundColor: colors.secondary,
  },
  planHardPassReasonChoices: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  planHardPassReasonChoice: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  planHardPassReasonChoiceSelected: {
    borderColor: colors.textPrimary,
    backgroundColor: colors.secondary,
  },
  planHardPassReasonChoiceText: { fontFamily: fonts.medium },
  planDrawerEmpty: {
    flex: 1,
    justifyContent: "center",
    marginTop: 0,
    paddingBottom: spacing["3xl"],
  },
  planDrawerSettlementDisabled: { opacity: 0.4 },
  planDrawerPlacementIntro: { gap: spacing.xs, paddingBottom: spacing.xs },
  planDrawerMainRow: { minHeight: 56, flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, paddingTop: 3 },
  planDrawerReactionRow: { minHeight: 32, minWidth: 0, flexDirection: "row", alignItems: "center", gap: spacing.xs },
  planViewGroceriesContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  planPlannedSectionHeading: {
    minHeight: 52,
    justifyContent: "flex-end",
    marginHorizontal: -spacing.xs,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
    borderRadius: radii.control,
  },
  planPlannedEmpty: {
    minHeight: 64,
    justifyContent: "center",
    marginHorizontal: -spacing.xs,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
    borderRadius: radii.control,
  },
  planPlannedMealArtworkFrame: {
    width: 56,
    height: 56,
    flexShrink: 0,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: colors.secondary,
  },
  planPlannedMealArtwork: { width: 56, height: 56, borderRadius: 14 },
  planTimingEditor: { width: "100%", gap: spacing.sm, paddingBottom: spacing.md },
  planTimingChoices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  planTimingChoice: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  planTimingChoiceSelected: { borderColor: colors.sumi900, backgroundColor: colors.fieldFill },
  planTimingInput: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.textPrimary,
    paddingHorizontal: spacing.sm,
  },
});
