import { StyleSheet } from "react-native";

import { colors, radii, spacing, typography } from "../../../theme";
import {
  RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
  RESTING_COMPOSER_HEIGHT_PX,
  RESTING_COMPOSER_HORIZONTAL_INSET_PX,
} from "../../../ui/layout/restingComposerMetrics";

const MEAL_PLAN_DRAWER_PEEK_HEIGHT = 124;

export const styles = StyleSheet.create({
  list: {
    paddingHorizontal: spacing.md,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.sm,
  },
  libraryHeader: {
    gap: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  discoveryList: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.lg,
  },
  inventoryControls: { gap: spacing.sm },
  controlRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  resultCount: { marginLeft: "auto", flexShrink: 0 },
  menuItemRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  mealsMenuContent: { width: 276, minWidth: 276 },
  menuServingRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  menuServingLabel: { flex: 1, minWidth: 0 },
  menuServingControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  menuServingButton: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuServingButtonDisabled: { opacity: 0.4 },
  menuServingButtonLabel: { ...typography.titleSm, lineHeight: 22 },
  menuServingCount: { ...typography.body, minWidth: 16, textAlign: "center" },
  mealPlanHeaderAction: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    backgroundColor: colors.fieldFill,
  },
  mealPlanHeaderLabel: { color: colors.textPrimary },
  mealPlanCountBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 5,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.destructive,
  },
  mealPlanCountText: {
    color: colors.primaryForeground,
    fontSize: 10,
    lineHeight: 12,
  },
  appliedFilters: { gap: spacing.xs, paddingRight: spacing.sm },
  appliedFilter: {
    minHeight: 34,
    paddingHorizontal: spacing.sm,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.secondary,
  },
  editorialOffer: {
    width: "100%",
    height: 104,
    overflow: "hidden",
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  editorialOfferPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },
  editorialOfferArtwork: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  editorialOfferShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(28,26,25,0.48)",
  },
  editorialOfferCopy: {
    position: "absolute",
    top: spacing.sm,
    bottom: spacing.sm,
    left: spacing.md,
    zIndex: 2,
    width: 184,
    justifyContent: "center",
    gap: spacing.xs,
  },
  editorialOfferEyebrow: {
    color: colors.primaryForeground,
    fontSize: 10,
    letterSpacing: 0.8,
  },
  editorialOfferTitle: { color: colors.primaryForeground },
  editorialOfferAction: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: spacing.xs,
  },
  editorialOfferActionText: { color: colors.primaryForeground },
  gridRow: { gap: spacing.sm },
  card: { flex: 1, minWidth: 0, marginBottom: spacing.md },
  shelfCard: { flex: 0, width: 164, marginBottom: 0 },
  cardArtworkFrame: { position: "relative" },
  cardArtwork: { width: "100%", aspectRatio: 1.15, borderRadius: 18 },
  planCardToggle: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
  },
  planCardToggleSelected: { backgroundColor: colors.sumi900 },
  cardBody: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.xs,
    gap: spacing.xs,
  },
  cardTitle: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 15,
    lineHeight: 19,
  },
  cardMeta: { ...typography.bodyXs },
  recommendationReason: { flexDirection: "row", alignItems: "center", gap: 4 },
  recommendationReasonText: {
    color: colors.pine700,
    fontSize: 11,
    lineHeight: 14,
  },
  shelf: { gap: spacing.sm },
  shelfHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  seeAll: {
    minHeight: 44,
    minWidth: 64,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingLeft: spacing.sm,
  },
  seeAllText: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 14,
    lineHeight: 20,
  },
  shelfContent: { gap: spacing.sm, paddingRight: spacing.md },
  pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] },
  empty: {
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.xl * 2,
    paddingHorizontal: spacing.md,
  },
  drawerContent: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  filterSection: { gap: spacing.sm },
  choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  filterChoice: {
    minHeight: 38,
    paddingHorizontal: spacing.md,
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChoiceSelected: {
    backgroundColor: colors.sumi900,
    borderColor: colors.sumi900,
  },
  filterChoiceTextSelected: { color: colors.canvas },
  drawerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  drawerApply: { flex: 1 },
  optionRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  optionCopy: { flex: 1, minWidth: 0, gap: 2 },
  optionSelected: {
    fontFamily: typography.titleSm.fontFamily,
    color: colors.accent,
  },
  captureRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  captureIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary,
  },
  dock: {
    position: "absolute",
    left: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    right: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    bottom: RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
    height: RESTING_COMPOSER_HEIGHT_PX,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 60,
    elevation: 60,
  },
  addDockButton: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  addDockSurface: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  addDockSurfaceContent: {
    height: RESTING_COMPOSER_HEIGHT_PX,
    justifyContent: "center",
  },
  addDockContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  planDrawerSearch: {
    position: "absolute",
    right: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    bottom: MEAL_PLAN_DRAWER_PEEK_HEIGHT + spacing.sm,
    zIndex: 70,
    elevation: 70,
  },
  planDrawerSheet: {
    paddingHorizontal: 0,
    paddingTop: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  planDrawerHandleRegion: { paddingTop: spacing.sm, paddingBottom: spacing.xs },
  planDrawerViewport: { flex: 1, minHeight: 0, overflow: "hidden" },
  planDrawerHeader: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
  },
  planDrawerHeaderMain: { flex: 1, minWidth: 0, gap: spacing.xs },
  planDrawerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planDrawerThumbnails: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  planDrawerThumbnailFrame: {
    width: 24,
    height: 24,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.canvas,
  },
  planDrawerThumbnail: { width: 24, height: 24, borderRadius: 12 },
  planDrawerOverflow: { marginLeft: 2, fontSize: 11, lineHeight: 15 },
  planDrawerClose: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  planDrawerContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl * 2,
    gap: spacing.md,
  },
  planDrawerList: { gap: spacing.xs },
  planDrawerRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  planDrawerArtworkFrame: {
    width: 48,
    height: 48,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: colors.secondary,
  },
  planDrawerArtwork: { width: 48, height: 48, borderRadius: 14 },
  planDrawerTitle: { flex: 1, minWidth: 0 },
  planDrawerEmpty: { gap: spacing.xs, paddingVertical: spacing.md },
});
