import { StyleSheet } from "react-native";

import { colors, radii, spacing, typography } from "../../../theme";
import {
  RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
  RESTING_COMPOSER_HEIGHT_PX,
  RESTING_COMPOSER_HORIZONTAL_INSET_PX,
} from "../../../ui/layout/restingComposerMetrics";

export const styles = StyleSheet.create({
  list: {
    paddingHorizontal: spacing.md,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.sm,
  },
  libraryHeader: {
    gap: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  discoveryList: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom:
      RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX +
      RESTING_COMPOSER_HEIGHT_PX +
      spacing.lg,
    gap: spacing.lg,
  },
  inventoryControls: { gap: spacing.sm },
  controlRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  resultCount: { marginLeft: "auto", flexShrink: 0 },
  menuItemRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  mealsMenuContent: { width: 276, minWidth: 276 },
  menuServingRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  menuServingLabel: { flex: 1, minWidth: 0 },
  menuServingControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  menuServingButton: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuServingButtonDisabled: { opacity: 0.4 },
  menuServingButtonLabel: { ...typography.titleSm, lineHeight: 22 },
  menuServingCount: { ...typography.body, minWidth: 16, textAlign: "center" },
  mealPlanHeaderAction: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radii.pill,
    backgroundColor: colors.fieldFill,
  },
  mealPlanHeaderLabel: { color: colors.textPrimary },
  mealPlanCountBadge: {
    minWidth: 18,
    height: 18,
    paddingHorizontal: 5,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.sumi900,
  },
  mealPlanCountText: {
    color: colors.primaryForeground,
    fontSize: 10,
    lineHeight: 12,
  },
  appliedFilters: { gap: spacing.xs, paddingRight: spacing.sm },
  appliedFilter: {
    minHeight: 34,
    paddingHorizontal: spacing.sm,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: colors.secondary,
  },
  cuisineSection: { gap: spacing.sm },
  cuisineRow: { gap: spacing.sm, paddingRight: spacing.md },
  cuisineCard: { width: 104, gap: spacing.xs },
  cuisineCardPressed: { opacity: 0.82, transform: [{ scale: 0.98 }] },
  cuisineArtwork: {
    width: 104,
    height: 104,
    borderRadius: radii.card,
    backgroundColor: colors.canvas,
  },
  cuisineLabel: { minHeight: 34, textAlign: "center" },
  cuisineRefinement: { gap: spacing.xs },
  cuisineRefinementRow: { gap: spacing.xs, paddingRight: spacing.md },
  cuisineRefinementChip: {
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: 17,
    backgroundColor: colors.secondary,
  },
  cuisineRefinementChipSelected: {
    borderWidth: 1,
    borderColor: colors.textPrimary,
  },
  editorialOffer: {
    width: "100%",
    height: 104,
    overflow: "hidden",
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  editorialOfferPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },
  editorialOfferArtwork: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  editorialOfferShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(28,26,25,0.48)",
  },
  editorialOfferCopy: {
    position: "absolute",
    top: spacing.sm,
    bottom: spacing.sm,
    left: spacing.md,
    zIndex: 2,
    width: 184,
    justifyContent: "center",
    gap: spacing.xs,
  },
  editorialOfferEyebrow: {
    color: colors.primaryForeground,
    fontSize: 10,
    letterSpacing: 0.8,
  },
  editorialOfferTitle: { color: colors.primaryForeground },
  editorialOfferAction: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: spacing.xs,
  },
  editorialOfferActionText: { color: colors.primaryForeground },
  gridRow: { gap: spacing.sm },
  card: { flex: 1, minWidth: 0, marginBottom: spacing.md },
  shelfCard: { flex: 0, width: 164, marginBottom: 0 },
  cardArtworkFrame: { position: "relative" },
  cardArtwork: { width: "100%", aspectRatio: 1.15, borderRadius: 18 },
  planCardToggle: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
  },
  planCardToggleSelected: { backgroundColor: colors.sumi900 },
  cardBody: {
    paddingTop: spacing.sm,
    paddingHorizontal: spacing.xs,
    gap: spacing.xs,
  },
  cardTitle: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 15,
    lineHeight: 19,
  },
  cardMeta: { ...typography.bodyXs },
  recommendationReason: { flexDirection: "row", alignItems: "center", gap: 4 },
  recommendationReasonText: {
    color: colors.pine700,
    fontSize: 11,
    lineHeight: 14,
  },
  shelf: { gap: spacing.sm },
  shelfHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  seeAll: {
    minHeight: 44,
    minWidth: 64,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingLeft: spacing.sm,
  },
  seeAllText: {
    fontFamily: typography.titleSm.fontFamily,
    fontSize: 14,
    lineHeight: 20,
  },
  shelfContent: { gap: spacing.sm, paddingRight: spacing.md },
  pressed: { opacity: 0.76, transform: [{ scale: 0.985 }] },
  empty: {
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.xl * 2,
    paddingHorizontal: spacing.md,
  },
  drawerContent: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  filterSection: { gap: spacing.sm },
  choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  filterChoice: {
    minHeight: 38,
    paddingHorizontal: spacing.md,
    justifyContent: "center",
    borderRadius: 19,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChoiceSelected: {
    backgroundColor: colors.sumi900,
    borderColor: colors.sumi900,
  },
  filterChoiceTextSelected: { color: colors.canvas },
  drawerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingTop: spacing.sm,
  },
  drawerApply: { flex: 1 },
  optionRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  optionCopy: { flex: 1, minWidth: 0, gap: 2 },
  optionSelected: {
    fontFamily: typography.titleSm.fontFamily,
    color: colors.accent,
  },
  captureRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  captureIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.secondary,
  },
  dock: {
    position: "absolute",
    left: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    right: RESTING_COMPOSER_HORIZONTAL_INSET_PX,
    bottom: RESTING_COMPOSER_COMPACT_BOTTOM_OFFSET_PX,
    height: RESTING_COMPOSER_HEIGHT_PX,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    zIndex: 60,
    elevation: 60,
  },
  addDockButton: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  addDockSurface: { flex: 1, height: RESTING_COMPOSER_HEIGHT_PX },
  addDockSurfaceContent: {
    height: RESTING_COMPOSER_HEIGHT_PX,
    justifyContent: "center",
  },
  addDockContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  planDrawerSheet: {
    paddingHorizontal: 0,
    paddingTop: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  planDrawerHandleRegion: { paddingTop: spacing.sm, paddingBottom: spacing.xs },
  planDrawerViewport: { flex: 1, minHeight: 0, overflow: "hidden" },
  planDrawerHeader: {
    minHeight: 64,
    paddingHorizontal: spacing.lg,
    justifyContent: "center",
  },
  planDrawerHeaderMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  planDrawerContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl * 2,
    gap: spacing.md,
  },
  committedPlanSection: { gap: spacing.md, paddingBottom: spacing.sm },
  committedPlanHeading: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: spacing.md },
  committedMealList: { gap: spacing.sm },
  committedMealCard: {
    minHeight: 96,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  committedMealArtwork: { width: 64, height: 64, borderRadius: 14 },
  committedMealCopy: { flex: 1, minWidth: 0, gap: 2 },
  committedMealTitle: { ...typography.titleSm, minWidth: 0 },
  planDrawerList: { gap: spacing.xs },
  planDrawerItem: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  planDrawerRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  planDrawerSelection: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  planDrawerSelectionActive: { backgroundColor: colors.sumi900, borderColor: colors.sumi900 },
  planDrawerArtworkFrame: {
    width: 48,
    height: 48,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: colors.secondary,
  },
  planDrawerArtwork: { width: 48, height: 48, borderRadius: 14 },
  planDrawerMealCopy: { flex: 1, minWidth: 0, gap: 2 },
  planDrawerTitle: { minWidth: 0 },
  planPeopleTrigger: { minHeight: 32, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: spacing.xs, borderRadius: 999, paddingHorizontal: spacing.xs },
  planPeopleMenu: { width: 240, gap: 2 },
  planDrawerEmpty: { gap: spacing.xs, paddingVertical: spacing.md },
  planDrawerSettlementDisabled: { opacity: 0.4 },
  planDrawerPlacementIntro: { gap: spacing.xs, paddingBottom: spacing.xs },
  planLifecycleGroup: { gap: spacing.xs },
  planLifecycleHeading: { minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  planDrawerMainRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: spacing.sm },
  planDrawerReactionRow: { minHeight: 36, marginLeft: 56, flexDirection: "row", alignItems: "center", gap: spacing.xs, paddingBottom: spacing.xs },
  planDrawerReactionRowSelecting: { marginLeft: 88 },
  planMissingItems: { marginLeft: "auto" },
  planSelectionActions: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  planSelectionConfirm: { flex: 1 },
  planTimingEditor: { width: "100%", gap: spacing.sm, paddingBottom: spacing.md },
  planTimingChoices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  planTimingChoice: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  planTimingChoiceSelected: { borderColor: colors.sumi900, backgroundColor: colors.fieldFill },
  planTimingInput: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.textPrimary,
    paddingHorizontal: spacing.sm,
  },
});
